# Configuration file for specifying the structure of the POMDP problem we're solving
n_agents: 2
n_nodes: 7
agents_structure: [7]     # For now, the state of the agents is just the node they are in
world_structure: [2,2,2]  # The world can have three different things in it: fire, a victim of debris

# Location of nodes in simplified 5x5 grid
node_locations: 
  1: [3,1]
  2: [5,1]
  3: [5,3]
  4: [3,3]
  5: [5,5]
  6: [1,5]
  7: [1,2]

# Connectivity of nodes: the connections existent between nodes
node_connectivity:
  1: [2] 
  2: [3,1]
  3: [5,2,4]
  4: [3]
  5: [3,6]
  6: [7,5]
  7: [6]

occupied_cells:
  - [1, 1]
  - [2, 1]
  - [2, 2]
  - [3, 2]
  - [4, 2]
  - [2, 3]
  - [2, 4]
  - [3, 4]
  - [4, 4]

# The vector of abilities describes each agent's inherent ability to perform an action.
# The number of actions available can be derived from the sum of the len of this vector
# and of the number of nodes.
# Semantic value of actions:
# [extinguish fire, extract victim, clear path]
#  1: should be done
#  0: able to do, but preferable not to
# -1: unable to do
agent_abilities:
    # UAV
    1: [1, -1, 0] 
    # UGV
    2: [1, -1, 1]