# Configuration file for specifying the structure of the POMDP problem we're solving
# Ambitious:
# n_agents: 5
# world_geometry:
#   X: 8 # Width of the world
#   Y: 8 # Height of the world
# # action_space:
# #   - 0 # Put out fire
# #   - 1 # Remove debris
# #   - 2 # Extract person
# #   - 3 # pick fire extinguisher 
# #   - 4 # stop 
# #   - 5 # send information 
# #   - 6 # explore 
# #   - 7 # Move to node 1 
# #   - 8 # Move to node 2 
# #   - 9 # Move to node 3
# #   - 10 # Move to node 4
# #   - 11 # Move to node 5
# #   - 12 # Move to node 6
# #   - 13 # Move to node 7
# #   - 14 # Move to node 8
# #   - 15 # Move to node 9
# #   - 16 # Move to node 10
# #   - 17 # Move to node 11
# #   - 18 # Move to node 12
# #   - 19 # Move to node 13
# #   - 20 # Move to node 14
# #   - 21 # Move to node 15
# #   - 22 # Move to node 16
# #   - 23 # Move to node 17
# #   - 24 # Move to node 18
# n_actions: 24 # 7 for problem-solving, the remainder for movement

# Conservative:
n_agents: 2
#world_geometry:# it is 2 nodes 
  #X: 2 # Width of the world
  #Y: 2 # Height of the world
# action_space:
#   - 0 # Put out fire
#   - 1 # Remove debris
#   - 2 # Extract person
#   - 3 # Move to node 1
#   - 4 # Move to node 2
n_actions: 8 # 3 for problem-solving, the remainder for movement
nodes_num: 7
agents_structure: 7 #it could be one of the 7 nodes 
world_structure: [2,2,2] # it has three objectives and each one either 0 or 1

#Node in 5x5 grid
nodes_location: 
  1: [3,1]
  2: [5,1]
  3: [5,3]
  4: [3,3]
  5: [5,5]
  6: [1,5]
  7: [1,2]

# nodes connectivtity to others [up, down, right, left]
nodes_connectivity:
  1: [0,0,2,0] 
  2: [3,0,0,1]
  3: [5,2,0,4]
  4: [0,0,3,0]
  5: [0,3,0,6]
  6: [0,7,5,0]
  7: [6,0,0,0]