# Configuration file for specifying the objectives and ground-truth structure of the world
initial_state:
  Agents:
    0: [2,2]
    1: [1,3]
# The "World" state is a matrix of lists, with each inner list corresponding to one cell
# of the world. Variables are defined as follows:
# [occupancy, fire, victim, debris]
  World:
    - [[0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0]] 
    - [[0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0]]
    - [[0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0]] 
    - [[0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0]] 
# This constant si multiplied by the probability of message delivery to modulate the
# inverse-square law to fit our needs.  
connectivity_constant: 1.0