# Configuration file for specifying the objectives and ground-truth structure of the world
# Ambitious
# initial_state:
#   Agents:
#     0: [2,2]
#     1: [1,3]
#     2: [4,4]
# # The "World" state is a matrix of lists, with each inner list corresponding to one cell
# # of the world. Variables are defined as follows:
# # [occupancy, fire, debris, victim]
#   World:
#     - [[1,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [1,0,0,0], [1,0,0,0], [0,0,0,1]] 
#     - [[1,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [0,1,0,0], [1,0,0,0], [1,0,0,0], [0,0,1,0]]
#     - [[1,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [1,0,0,0], [1,0,0,0], [0,1,0,0]]
#     - [[1,0,0,0], [1,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [0,1,0,0], [1,0,0,0], [0,0,0,0]]
#     - [[1,0,0,0], [1,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [1,0,0,0], [1,0,0,0], [0,0,0,0]]
#     - [[1,0,0,0], [1,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,1,0], [0,0,1,0], [0,0,0,0], [0,0,0,0]]
#     - [[1,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,1], [0,0,1,0], [0,0,1,0], [0,0,0,0], [0,0,0,0]]
#     - [[1,0,0,0], [0,1,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0]]
# # This constant is multiplied by the probability of message delivery to modulate the
# # inverse-square law to fit our needs.  
# connectivity_constant: 1.0

# Conservative:
initial_state:
  Agents:
    0: [0,0]
    1: [1,1]
# The "World" state is a matrix of lists, with each inner list corresponding to one cell
# of the world. Variables are defined as follows:
# [occupancy, fire, debris, victim]
  World:
    - [[1,0,0,0], [0,0,0,0]] 
    - [[1,0,0,0], [0,0,0,0]]
# This constant is multiplied by the probability of message delivery to modulate the
# inverse-square law to fit our needs.  
connectivity_constant: 1.0