# Configuration file for specifying the objectives and ground-truth structure of the world
# Conservative:
initial_state:
  Agents:
    1: [5] #UGV
    2: [7] #UAV
# This list contains an element for each node in the world:
# [fire, debris, victim]
  World:
    [[1,0,0], #node 1
     [0,0,2], #node 2
     [0,1,0], #node 3
     [1,0,0], #node 4
     [0,0,0], #node 5
     [0,0,0], #node 6
     [0,0,0]] #node 7 

# This constant is multiplied by the probability of message delivery to modulate the
# inverse-square law to fit our needs.  
connectivity_constant: 1.0


     